test: off
build_script:
    - ps: .\build.ps1
artifacts:
    - path: packaging\*.nupkg
deploy:
    provider: NuGet
    api_key:
        secure: jIk7hDIpgOtyTG6FPxA3s55xN1pxaiJIBTeJrGlV664POb4pGAVdr90zFLt3jmDy
    artifact: /.*\.nupkg/
